name: Matrix demo
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, window-latest]
        include: # add standalone combinations
          - node-version: 18
            operating-system: ubuntu-latest
            # npm: 6 # brand new key-vals supported
        exclude:
          - node-version: 12
            operating-system: window-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Deps
        run: npm ci
      - name: Build project
        run: npm run build
