name: Reusable deploy
on: workflow_call # must be callable by other workflows
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output info
        run: echo "deploying and uploading..."
